[package]
name = "serde_derive"
version = "0.8.20"
authors = ["Erick Tryzelaar <erick.tryzelaar@gmail.com>"]
license = "MIT/Apache-2.0"
description = "Macros 1.1 implementation of #[derive(Serialize, Deserialize)]"
homepage = "https://serde.rs"
repository = "https://github.com/serde-rs/serde"
documentation = "https://serde.rs/codegen.html"
keywords = ["serde", "serialization"]
include = ["Cargo.toml", "src/**/*.rs"]

[lib]
name = "serde_derive"
proc-macro = true

[dependencies.serde_codegen]
version = "=0.8.20"
path = "../serde_codegen"
default-features = false
features = ["with-syn"]

[dev-dependencies]
compiletest_rs = "^0.2.0"
fnv = "1.0"
serde = { version = "0.8.20", path = "../serde" }
serde_test = { version = "0.8.20", path = "../serde_test" }
